[colors]
ansi = [
    '#2d302f',
    '#f9906f',
    '#8ab361',
    '#f0c239',
    '#b0a4e3',
    '#cca4e3',
    '#30dff3',
    '#e0f0ef',
]
background = '#2d302f'
brights = [
    '#9da8a3',
    '#f9906f',
    '#8ab361',
    '#f0c239',
    '#b0a4e3',
    '#cca4e3',
    '#30dff3',
    '#fcfefd',
]
cursor_bg = '#00ff00'
cursor_border = '#ff0000'
cursor_fg = '#434846'
foreground = '#e0f0ef'
selection_bg = '#e0f0ef'
selection_fg = '#2d302f'

[colors.indexed]

[metadata]
aliases = []
author = 'David Park (dpjungmin) (dpjungmin@gmail.com)'
name = 'tissue'
