[colors]
foreground = "#b7bcba"
background = "#161719"

cursor_fg = "#000000"
cursor_bg = "#00ff00"
cursor_border = "#ff0000"

selection_fg = "None"
selection_bg = "#434846"

split = "#444c56"

ansi = [
  "#2a2e33", # DARK-BLACK
  "#b84d51", # DARK-RED
  "#b3bf5a", # DARK-GREEN
  "#e4b55e", # DARK-YELLOW
  "#6e90b0", # DARK-BLUE
  "#a17eac", # DARK-MAGENTA
  "#7fbfb4", # DARK-CYAN
  "#b5b9b6"  # DARK-WHITE
]

brights = [
  "#1d1f22", # BRIGHT-BLACK
  "#8d2e32", # BRIGHT-RED
  "#798431", # BRIGHT-GREEN
  "#e58a50", # BRIGHT-YELLOW
  "#4b6b88", # BRIGHT-BLUE
  "#6e5079", # BRIGHT-MAGENTA
  "#4d7b74", # BRIGHT-CYAN
  "#5a626a"  # BRIGHT-WHITE
]

compose_cursor = "orange"
